"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Plus } from "lucide-react";

const faqs = [
  {
    question: "How does HG HEALING personalize my learning experience?",
    answer: "Our AI engine analyzes your interaction patterns, sales metrics, and course progress to dynamically suggest modules that target your specific skill gaps."
  },
  {
    question: "Can I integrate my existing CRM with the platform?",
    answer: "Yes, we offer one-click integrations with Salesforce, HubSpot, and Pipedrive on our Professional and Enterprise plans."
  },
  {
    question: "How is the impact score calculated for courses?",
    answer: "Impact scores are generated by evaluating the post-course sales performance of past students compared to their historical baselines."
  },
  {
    question: "What happens when I reach my monthly usage limits?",
    answer: "You will continue to have access to your courses, but AI automation tasks will be paused until the next billing cycle unless you choose to upgrade."
  },
  {
    question: "Which payment options are available?",
    answer: "We accept all major credit cards, PayPal, and wire transfers for Enterprise annual billing."
  },
  {
    question: "Do you have an affiliate program?",
    answer: "Yes! Our partners earn a 20% recurring commission for every new active subscriber they refer to HG HEALING."
  }
];

export function Faq() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="w-full px-6 py-32 relative flex flex-col items-center z-40">
      {/* Background Soft Glow */}
      <div className="absolute top-1/2 left-0 -translate-y-1/2 w-[600px] h-[600px] bg-white/[0.03] blur-[150px] rounded-full pointer-events-none -translate-x-1/3" />

      <div className="w-full max-w-3xl mx-auto flex flex-col items-center z-10">

        {/* Header */}
        <div className="text-center mb-16">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-4xl md:text-[44px] font-medium tracking-tight text-white mb-6"
          >
            Frequently Asked Questions
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-gray-400 text-sm max-w-lg mx-auto leading-relaxed"
          >
            If you can't find an answer here, check out the community forum, reach out on Twitter, or write to <span className="text-gray-200">support@fusionai.com</span>.
          </motion.p>
        </div>

        {/* FAQ Accordion */}
        <div className="w-full flex flex-col gap-3">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;

            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1, duration: 0.5, ease: "easeOut" }}
                className="w-full bg-[#111] rounded-2xl overflow-hidden border border-white/[0.02] hover:bg-[#151515] transition-colors"
              >
                <button
                  onClick={() => toggleFaq(index)}
                  className="w-full flex items-center justify-between px-8 py-5 text-left"
                >
                  <span className="text-gray-200 font-medium text-[15px] pr-8">{faq.question}</span>
                  <motion.div
                    animate={{ rotate: isOpen ? 45 : 0 }}
                    transition={{ duration: 0.3, ease: "easeInOut" }}
                    className="shrink-0 p-0.5 bg-blue-400 rounded-full"
                  >
                    <Plus className="w-5 h-5 text-black" />
                  </motion.div>
                </button>

                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: "easeInOut" }}
                    >
                      <div className="px-8 pb-6 text-gray-400 text-sm leading-relaxed">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
