import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ImageKitProviderWrapper } from "@/components/ImageKitProviderWrapper";
import { Toaster } from "sonner";
import { SilenceScriptWarning } from "@/components/SilenceScriptWarning";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
        lang="en"
        className={`${poppins.variable} h-full antialiased`}
        suppressHydrationWarning
      >
        <body suppressHydrationWarning className="min-h-full flex flex-col font-sans transition-colors">
          <SilenceScriptWarning />
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={true}>
            <ImageKitProviderWrapper>
              {children}
              <Toaster position="top-center" richColors />
            </ImageKitProviderWrapper>
          </ThemeProvider>
        </body>
      </html>
  );
}
